// Superseded by next.config.ts (Next.js 16 native TypeScript config).
// Do not edit this file — edit next.config.ts instead.
/** @type {import('next').NextConfig} */
const nextConfig = {}
export default nextConfig
